#!/usr/bin/env python
import serial,os,sys,time,tty,termios
from pylab import *

devs = [s for s in os.listdir('/dev') if 'ttyUSB' in s]

MAXBYTES = 1000
baudrate = 9600
port     = '/dev/'+devs[0]


print devs


def startSerial():
    os.system('stty -F %s 9600 cs8 cread'%port)
    ser = serial.Serial(port,baudrate,timeout=0)
    time.sleep(.1)
    if not ser.isOpen():
        print 'CONNECTION FAILED'
        sys.exit(0)
    print 'SUCCESS'
    return ser
    
def closeSerial(ser):
    ser.close()
    print 'CLOSED' 

ser = startSerial()

while(1):
    for i in range(256):
        ser.write(chr(i))
        for i in xrange(1000):
            for j in xrange(100):
                pass

for i in xrange(100):
    try:
        print ord(ser.read())
    except:
        pass
        
closeSerial(ser)





